name: Clojure CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.0
      with:
        # Install just one or all simultaneously
        # The value must indicate a particular version of the tool, or use 'latest'
        # to always provision the latest version
        cli: 1.10.1.693              # Clojure CLI based on tools.deps
        lein: 2.9.1                  # Leiningen
        boot: 2.8.3                  # Boot.clj
        bb: 0.7.8                    # Babashka
        clj-kondo: 2022.05.31        # Clj-kondo
        cljstyle: 0.15.0             # cljstyle
        cmd-exe-workaround: 'latest' # Replaces `clojure` with `deps.clj` on Windows
        zprint: 1.2.3                # zprint
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
